### ISSUE TITLE
代码结构不应该有大变化

### ISSUE THREAD

**Issue by woty** [Jueast/BUAA_MIPS_OS_ARM_Porting#1]
应该以porting的方式修改原有MIPS实验代码，建议保留driver目录，在其中建立raspberry2子目录，包含硬件相关的代码，lib目录中尽量不包含硬件相关的代码，相关接口尽量保持不变。

**Comment by Jueast** [comment]
明白意思了, 硬件相关都放driver，然后lib放操作系统相关库的代码，感觉很ok。相关接口具体是指？

**Comment by woty** [comment]
lib尽量不变，这是暴露给用户程序的接口（实现）；lib里调用drivers里的函数接口尽量不变，比如lib/printf.c里面调用的printchar函数，这是os类库和硬件之间的接口，接口型构不变，实现可以不同。

**Comment by Jueast** [comment]
已经做了相应调整，应该可以了。：）
